---
apiVersion: v1
kind: Service
metadata:
  name: database-tier-service
  namespace: default
spec:
  selector:
    app: database-tier
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
