---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-tier-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-tier
  template:
    metadata:
      labels:
        app: database-tier
    spec:
      securityContext:
        fsGroup: 999 # GID of 'mysql' user in the container
        runAsUser: 999
      containers:
      - name: database-tier
        image: mysql:1.2.1
        imagePullPolicy: Always
        volumeMounts:
        - name: tellmejoke-pv
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysecretpassword
      volumes:
      - name: tellmejoke-pv
        persistentVolumeClaim:
          claimName: tellmejoke-pvc