apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tellmejoke-databasetier
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kozraf/tellmejoke.git'
    targetRevision: basic-3tierapp-argocd
    path: DatabaseTier
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}