apiVersion: batch/v1
kind: Job
metadata:
  name: database-init-job
  namespace: default
spec:
  template:
    spec:
      initContainers:
      - name: check-database-ready
        image: appropriate/curl
        command:
        - "sh"
        - "-c"
        - |
          until nc -z database-tier-service 3306; do
            echo "Waiting for database-tier-deployment to be ready..."
            sleep 10
          done
      containers:
      - name: database-init
        image: kozraf/tellmejoke-databasetier:latest
        env:
        - name: MYSQL_HOST
          value: database-tier-service
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: mysecretpassword
        args:
        - /bin/bash
        - -c
        - |
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD < /docker-entrypoint-initdb.d/init.sql
      restartPolicy: Never

