apiVersion: batch/v1
kind: Job
metadata:
  name: database-init-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: database-init
        image: kozraf/tellmejoke-databasetier:latest
        env:
        - name: MYSQL_HOST
          value: database-tier-service
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: mysecretpassword
        args:
        - /bin/bash
        - -c
        - |
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD < /docker-entrypoint-initdb.d/init.sql
      restartPolicy: Never
