apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        fsGroup: 999 # GID of 'mysql' user in the container
        runAsUser: 999
      containers:
      - name: mysql
        image: mysql:latest
        volumeMounts:
        - name: tellmejoke-pv
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysecretpassword
      volumes:
      - name: tellmejoke-pv
        persistentVolumeClaim:
          claimName: tellmejoke-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentation-tier-deployment
  labels:
    app: presentation-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presentation-tier
  template:
    metadata:
      labels:
        app: presentation-tier
    spec:
      containers:
      - name: presentation-tier
        image: kozraf/tellmejoke-presentationtier:v1.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-tier-deployment
  labels:
    app: business-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-tier
  template:
    metadata:
      labels:
        app: business-tier
    spec:
      containers:
      - name: business-tier
        image: kozraf/tellmejoke-businesstier:v1.0
        ports:
        - containerPort: 80