apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data"]
        volumeMounts:
        - name: tellmejoke-pv
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:13.2
        volumeMounts:
        - name: tellmejoke-pv
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
      volumes:
      - name: tellmejoke-pv
        persistentVolumeClaim:
          claimName: tellmejoke-pvc
