apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:  # Add this section
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: postgres
        image: postgres:latest
        securityContext:  # Add this section
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: tellmejoke-pv
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
      volumes:
      - name: tellmejoke-pv
        persistentVolumeClaim:
          claimName: tellmejoke-pvc
