apiVersion: v1
kind: PersistentVolume
metadata:
  name: tellmejoke-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /srv/nfs/k8s/tellmejoke_app-pv
    server: 192.168.89.141