apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tellmejoke-presentationtier
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kozraf/tellmejoke.git'
    targetRevision: dev
    path: PresentationTier
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}