apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tellmejoke-presentationtier
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: 'PresentationTier'
    repoURL: 'https://github.com/kozraf/tellmejoke'
    targetRevision: v1.3
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true