apiVersion: v1
kind: Service
metadata:
  name: presentation-tier-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30089
  selector:
    app: presentation-tier
