name: Docker Build & Push
on:
  push:
    branches:
      - basic-3tierapp-argocd

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set DOCKER_BUILDKIT environment variable
        run: echo 'DOCKER_BUILDKIT=1' >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Database Tier Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: DatabaseTier
          file: DatabaseTier/Dockerfile
          push: true
          tags: kozraf/tellmejoke-databasetier:1.2.2

      - name: Build and Push Business Tier Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: BusinessTier
          file: BusinessTier/Dockerfile
          push: true
          tags: kozraf/tellmejoke-businesstier:1.2.2

      - name: Build and Push Presentation Tier Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: PresentationTier
          file: PresentationTier/Dockerfile
          push: true
          tags: kozraf/tellmejoke-presentationtier:1.2.2
