name: Docker Build & Push
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Dockerfile1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: BusinessTier/Dockerfile
          push: true
          tags: kozraf/tellmejoke-businesstier:latest

      - name: Build and Push Dockerfile2
        uses: docker/build-push-action@v2 --progress plain
        with:
          context: .
          file: PresentationTier/Dockerfile
          push: true
          tags: kozraf/tellmejoke-presentationtierlatest
